export const GAME_TIMING = {
  selectSeconds: 0.14,
  pour: {
    travelSeconds: 0.23,
    tiltStartSeconds: 0.09,
    tiltSeconds: 0.24,
    streamStartSeconds: 0.3,
    streamOpenSeconds: 0.07,
    transferStartSeconds: 0.35,
    transferSeconds: 0.34,
    streamCloseSeconds: 0.69,
    streamCloseDurationSeconds: 0.08,
    returnRotationSeconds: 0.79,
    returnRotationDurationSeconds: 0.18,
    returnTravelSeconds: 0.86,
    returnTravelDurationSeconds: 0.18,
    totalSeconds: 1.34,
  },
  undoSeconds: 0.24,
  restartSeconds: 0.22,
  completedVialSeconds: 0.26,
  completionHoldSeconds: 0.25,
} as const;
